name: Deploy to VPS

on:
  push:
    tags:
      - "v*.*.*-strategy-*"

jobs:
  build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Extract build context from tag
        id: extract_context
        run: |
          echo "Tag is $GITHUB_REF_NAME"
          # Extract substring after "-strategy-"
          CONTEXT=./rag-services/strategy-${GITHUB_REF_NAME#*-strategy-}/dist
          echo "Extracted context: $CONTEXT"
          echo "context=$CONTEXT" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          # Use the output from the previous step as the build context
          context: ${{ steps.extract_context.outputs.context }}
          file: ${{ steps.extract_context.outputs.context }}/Dockerfile
          push: true
          tags: |
            ghcr.io/hrnph/hrnph-qa-rag:${{ github.ref_name }}
            ghcr.io/hrnph/hrnph-qa-rag:latest
          cache-from: type=registry,ref=ghcr.io/hrnph/hrnph-qa-rag:buildcache
          cache-to: type=registry,ref=ghcr.io/hrnph/hrnph-qa-rag:buildcache,mode=max

  cleanup-on-failure:
    name: Cleanup on Failure
    runs-on: ubuntu-latest
    needs: build-push
    if: failure()

    steps:
      - name: Delete Release
        run: |
          echo "Deleting release ${{ github.ref_name }}"
          gh release delete ${{ github.ref_name }} --yes || true

  deploy-on-success:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build-push
    if: success()

    steps:
      - name: Do Nothing
        run: echo "Do nothing"
